// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/wabao/mogame/protocol/dto/RequestDto_Proto.proto

package com.wabao.mogame.protocol.dto;

public final class RequestDtoProto {
  private RequestDtoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestDtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 sn = 1;
    /**
     * <code>optional int32 sn = 1;</code>
     */
    boolean hasSn();
    /**
     * <code>optional int32 sn = 1;</code>
     */
    int getSn();

    // optional string method = 2;
    /**
     * <code>optional string method = 2;</code>
     */
    boolean hasMethod();
    /**
     * <code>optional string method = 2;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>optional string method = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    // repeated string params = 3;
    /**
     * <code>repeated string params = 3;</code>
     */
    java.util.List<java.lang.String>
    getParamsList();
    /**
     * <code>repeated string params = 3;</code>
     */
    int getParamsCount();
    /**
     * <code>repeated string params = 3;</code>
     */
    java.lang.String getParams(int index);
    /**
     * <code>repeated string params = 3;</code>
     */
    com.google.protobuf.ByteString
        getParamsBytes(int index);
  }
  /**
   * Protobuf type {@code com.wabao.mogame.protocol.dto.RequestDto}
   */
  public static final class RequestDto extends
      com.google.protobuf.GeneratedMessage
      implements RequestDtoOrBuilder {
    // Use RequestDto.newBuilder() to construct.
    private RequestDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestDto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestDto defaultInstance;
    public static RequestDto getDefaultInstance() {
      return defaultInstance;
    }

    public RequestDto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sn_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              method_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                params_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              params_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          params_ = new com.google.protobuf.UnmodifiableLazyStringList(params_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wabao.mogame.protocol.dto.RequestDtoProto.internal_static_com_wabao_mogame_protocol_dto_RequestDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wabao.mogame.protocol.dto.RequestDtoProto.internal_static_com_wabao_mogame_protocol_dto_RequestDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto.class, com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestDto> PARSER =
        new com.google.protobuf.AbstractParser<RequestDto>() {
      public RequestDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestDto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestDto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 sn = 1;
    public static final int SN_FIELD_NUMBER = 1;
    private int sn_;
    /**
     * <code>optional int32 sn = 1;</code>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 sn = 1;</code>
     */
    public int getSn() {
      return sn_;
    }

    // optional string method = 2;
    public static final int METHOD_FIELD_NUMBER = 2;
    private java.lang.Object method_;
    /**
     * <code>optional string method = 2;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string method = 2;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string params = 3;
    public static final int PARAMS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList params_;
    /**
     * <code>repeated string params = 3;</code>
     */
    public java.util.List<java.lang.String>
        getParamsList() {
      return params_;
    }
    /**
     * <code>repeated string params = 3;</code>
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated string params = 3;</code>
     */
    public java.lang.String getParams(int index) {
      return params_.get(index);
    }
    /**
     * <code>repeated string params = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParamsBytes(int index) {
      return params_.getByteString(index);
    }

    private void initFields() {
      sn_ = 0;
      method_ = "";
      params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sn_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodBytes());
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeBytes(3, params_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sn_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(params_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wabao.mogame.protocol.dto.RequestDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wabao.mogame.protocol.dto.RequestDtoProto.internal_static_com_wabao_mogame_protocol_dto_RequestDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wabao.mogame.protocol.dto.RequestDtoProto.internal_static_com_wabao_mogame_protocol_dto_RequestDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto.class, com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto.Builder.class);
      }

      // Construct using com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        method_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wabao.mogame.protocol.dto.RequestDtoProto.internal_static_com_wabao_mogame_protocol_dto_RequestDto_descriptor;
      }

      public com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto getDefaultInstanceForType() {
        return com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto.getDefaultInstance();
      }

      public com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto build() {
        com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto buildPartial() {
        com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto result = new com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sn_ = sn_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.method_ = method_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          params_ = new com.google.protobuf.UnmodifiableLazyStringList(
              params_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.params_ = params_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto) {
          return mergeFrom((com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto other) {
        if (other == com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto.getDefaultInstance()) return this;
        if (other.hasSn()) {
          setSn(other.getSn());
        }
        if (other.hasMethod()) {
          bitField0_ |= 0x00000002;
          method_ = other.method_;
          onChanged();
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wabao.mogame.protocol.dto.RequestDtoProto.RequestDto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 sn = 1;
      private int sn_ ;
      /**
       * <code>optional int32 sn = 1;</code>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 sn = 1;</code>
       */
      public int getSn() {
        return sn_;
      }
      /**
       * <code>optional int32 sn = 1;</code>
       */
      public Builder setSn(int value) {
        bitField0_ |= 0x00000001;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sn = 1;</code>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = 0;
        onChanged();
        return this;
      }

      // optional string method = 2;
      private java.lang.Object method_ = "";
      /**
       * <code>optional string method = 2;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }

      // repeated string params = 3;
      private com.google.protobuf.LazyStringList params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          params_ = new com.google.protobuf.LazyStringArrayList(params_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string params = 3;</code>
       */
      public java.util.List<java.lang.String>
          getParamsList() {
        return java.util.Collections.unmodifiableList(params_);
      }
      /**
       * <code>repeated string params = 3;</code>
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <code>repeated string params = 3;</code>
       */
      public java.lang.String getParams(int index) {
        return params_.get(index);
      }
      /**
       * <code>repeated string params = 3;</code>
       */
      public com.google.protobuf.ByteString
          getParamsBytes(int index) {
        return params_.getByteString(index);
      }
      /**
       * <code>repeated string params = 3;</code>
       */
      public Builder setParams(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 3;</code>
       */
      public Builder addParams(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 3;</code>
       */
      public Builder addAllParams(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamsIsMutable();
        super.addAll(values, params_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 3;</code>
       */
      public Builder clearParams() {
        params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 3;</code>
       */
      public Builder addParamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wabao.mogame.protocol.dto.RequestDto)
    }

    static {
      defaultInstance = new RequestDto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wabao.mogame.protocol.dto.RequestDto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wabao_mogame_protocol_dto_RequestDto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wabao_mogame_protocol_dto_RequestDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4com/wabao/mogame/protocol/dto/RequestD" +
      "to_Proto.proto\022\035com.wabao.mogame.protoco" +
      "l.dto\"8\n\nRequestDto\022\n\n\002sn\030\001 \001(\005\022\016\n\006metho" +
      "d\030\002 \001(\t\022\016\n\006params\030\003 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wabao_mogame_protocol_dto_RequestDto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wabao_mogame_protocol_dto_RequestDto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wabao_mogame_protocol_dto_RequestDto_descriptor,
              new java.lang.String[] { "Sn", "Method", "Params", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
