// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/wabao/mogame/protocol/dto/ProtoBufDto_Proto.proto

package com.wabao.mogame.protocol.dto;

public final class ProtoBufDtoProto {
  private ProtoBufDtoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtoBufDtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string typeName = 1;
    /**
     * <code>optional string typeName = 1;</code>
     */
    boolean hasTypeName();
    /**
     * <code>optional string typeName = 1;</code>
     */
    java.lang.String getTypeName();
    /**
     * <code>optional string typeName = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeNameBytes();

    // optional bytes data = 2;
    /**
     * <code>optional bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.wabao.mogame.protocol.dto.ProtoBufDto}
   *
   * <pre>
   **
   *字段列表:
   *typeName	null
   *data	null
   * </pre>
   */
  public static final class ProtoBufDto extends
      com.google.protobuf.GeneratedMessage
      implements ProtoBufDtoOrBuilder {
    // Use ProtoBufDto.newBuilder() to construct.
    private ProtoBufDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoBufDto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoBufDto defaultInstance;
    public static ProtoBufDto getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoBufDto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoBufDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              typeName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wabao.mogame.protocol.dto.ProtoBufDtoProto.internal_static_com_wabao_mogame_protocol_dto_ProtoBufDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wabao.mogame.protocol.dto.ProtoBufDtoProto.internal_static_com_wabao_mogame_protocol_dto_ProtoBufDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto.class, com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoBufDto> PARSER =
        new com.google.protobuf.AbstractParser<ProtoBufDto>() {
      public ProtoBufDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoBufDto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoBufDto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string typeName = 1;
    public static final int TYPENAME_FIELD_NUMBER = 1;
    private java.lang.Object typeName_;
    /**
     * <code>optional string typeName = 1;</code>
     */
    public boolean hasTypeName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string typeName = 1;</code>
     */
    public java.lang.String getTypeName() {
      java.lang.Object ref = typeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          typeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string typeName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeNameBytes() {
      java.lang.Object ref = typeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      typeName_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wabao.mogame.protocol.dto.ProtoBufDto}
     *
     * <pre>
     **
     *字段列表:
     *typeName	null
     *data	null
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wabao.mogame.protocol.dto.ProtoBufDtoProto.internal_static_com_wabao_mogame_protocol_dto_ProtoBufDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wabao.mogame.protocol.dto.ProtoBufDtoProto.internal_static_com_wabao_mogame_protocol_dto_ProtoBufDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto.class, com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto.Builder.class);
      }

      // Construct using com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        typeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wabao.mogame.protocol.dto.ProtoBufDtoProto.internal_static_com_wabao_mogame_protocol_dto_ProtoBufDto_descriptor;
      }

      public com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto getDefaultInstanceForType() {
        return com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto.getDefaultInstance();
      }

      public com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto build() {
        com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto buildPartial() {
        com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto result = new com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.typeName_ = typeName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto) {
          return mergeFrom((com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto other) {
        if (other == com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto.getDefaultInstance()) return this;
        if (other.hasTypeName()) {
          bitField0_ |= 0x00000001;
          typeName_ = other.typeName_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wabao.mogame.protocol.dto.ProtoBufDtoProto.ProtoBufDto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string typeName = 1;
      private java.lang.Object typeName_ = "";
      /**
       * <code>optional string typeName = 1;</code>
       */
      public boolean hasTypeName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string typeName = 1;</code>
       */
      public java.lang.String getTypeName() {
        java.lang.Object ref = typeName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          typeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string typeName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeNameBytes() {
        java.lang.Object ref = typeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          typeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string typeName = 1;</code>
       */
      public Builder setTypeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        typeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string typeName = 1;</code>
       */
      public Builder clearTypeName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        typeName_ = getDefaultInstance().getTypeName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string typeName = 1;</code>
       */
      public Builder setTypeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        typeName_ = value;
        onChanged();
        return this;
      }

      // optional bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wabao.mogame.protocol.dto.ProtoBufDto)
    }

    static {
      defaultInstance = new ProtoBufDto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wabao.mogame.protocol.dto.ProtoBufDto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wabao_mogame_protocol_dto_ProtoBufDto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wabao_mogame_protocol_dto_ProtoBufDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5com/wabao/mogame/protocol/dto/ProtoBuf" +
      "Dto_Proto.proto\022\035com.wabao.mogame.protoc" +
      "ol.dto\"-\n\013ProtoBufDto\022\020\n\010typeName\030\001 \001(\t\022" +
      "\014\n\004data\030\002 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wabao_mogame_protocol_dto_ProtoBufDto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wabao_mogame_protocol_dto_ProtoBufDto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wabao_mogame_protocol_dto_ProtoBufDto_descriptor,
              new java.lang.String[] { "TypeName", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
