// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/wabao/mogame/protocol/dto/player/PlayerDto_Proto.proto

package com.wabao.mogame.modules.protocol.dto;

public final class PlayerDtoProto {
  private PlayerDtoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerDtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;
    /**
     * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
     */
    java.util.List<com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto> 
        getPlayeritemsList();
    /**
     * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
     */
    com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto getPlayeritems(int index);
    /**
     * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
     */
    int getPlayeritemsCount();
    /**
     * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
     */
    java.util.List<? extends com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDtoOrBuilder> 
        getPlayeritemsOrBuilderList();
    /**
     * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
     */
    com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDtoOrBuilder getPlayeritemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.wabao.mogame.protocol.dto.player.PlayerDto}
   *
   * <pre>
   **
   *字段列表:
   *playeritems	null
   * </pre>
   */
  public static final class PlayerDto extends
      com.google.protobuf.GeneratedMessage
      implements PlayerDtoOrBuilder {
    // Use PlayerDto.newBuilder() to construct.
    private PlayerDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerDto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerDto defaultInstance;
    public static PlayerDto getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerDto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                playeritems_ = new java.util.ArrayList<com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto>();
                mutable_bitField0_ |= 0x00000001;
              }
              playeritems_.add(input.readMessage(com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          playeritems_ = java.util.Collections.unmodifiableList(playeritems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.internal_static_com_wabao_mogame_protocol_dto_player_PlayerDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.internal_static_com_wabao_mogame_protocol_dto_player_PlayerDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto.class, com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerDto> PARSER =
        new com.google.protobuf.AbstractParser<PlayerDto>() {
      public PlayerDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerDto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerDto> getParserForType() {
      return PARSER;
    }

    // repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;
    public static final int PLAYERITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto> playeritems_;
    /**
     * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
     */
    public java.util.List<com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto> getPlayeritemsList() {
      return playeritems_;
    }
    /**
     * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
     */
    public java.util.List<? extends com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDtoOrBuilder> 
        getPlayeritemsOrBuilderList() {
      return playeritems_;
    }
    /**
     * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
     */
    public int getPlayeritemsCount() {
      return playeritems_.size();
    }
    /**
     * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
     */
    public com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto getPlayeritems(int index) {
      return playeritems_.get(index);
    }
    /**
     * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
     */
    public com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDtoOrBuilder getPlayeritemsOrBuilder(
        int index) {
      return playeritems_.get(index);
    }

    private void initFields() {
      playeritems_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < playeritems_.size(); i++) {
        output.writeMessage(1, playeritems_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < playeritems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, playeritems_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wabao.mogame.protocol.dto.player.PlayerDto}
     *
     * <pre>
     **
     *字段列表:
     *playeritems	null
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.internal_static_com_wabao_mogame_protocol_dto_player_PlayerDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.internal_static_com_wabao_mogame_protocol_dto_player_PlayerDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto.class, com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto.Builder.class);
      }

      // Construct using com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayeritemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (playeritemsBuilder_ == null) {
          playeritems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          playeritemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.internal_static_com_wabao_mogame_protocol_dto_player_PlayerDto_descriptor;
      }

      public com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto getDefaultInstanceForType() {
        return com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto.getDefaultInstance();
      }

      public com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto build() {
        com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto buildPartial() {
        com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto result = new com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto(this);
        int from_bitField0_ = bitField0_;
        if (playeritemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            playeritems_ = java.util.Collections.unmodifiableList(playeritems_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.playeritems_ = playeritems_;
        } else {
          result.playeritems_ = playeritemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto) {
          return mergeFrom((com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto other) {
        if (other == com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto.getDefaultInstance()) return this;
        if (playeritemsBuilder_ == null) {
          if (!other.playeritems_.isEmpty()) {
            if (playeritems_.isEmpty()) {
              playeritems_ = other.playeritems_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlayeritemsIsMutable();
              playeritems_.addAll(other.playeritems_);
            }
            onChanged();
          }
        } else {
          if (!other.playeritems_.isEmpty()) {
            if (playeritemsBuilder_.isEmpty()) {
              playeritemsBuilder_.dispose();
              playeritemsBuilder_ = null;
              playeritems_ = other.playeritems_;
              bitField0_ = (bitField0_ & ~0x00000001);
              playeritemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPlayeritemsFieldBuilder() : null;
            } else {
              playeritemsBuilder_.addAllMessages(other.playeritems_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wabao.mogame.modules.protocol.dto.PlayerDtoProto.PlayerDto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;
      private java.util.List<com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto> playeritems_ =
        java.util.Collections.emptyList();
      private void ensurePlayeritemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          playeritems_ = new java.util.ArrayList<com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto>(playeritems_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.Builder, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDtoOrBuilder> playeritemsBuilder_;

      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public java.util.List<com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto> getPlayeritemsList() {
        if (playeritemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(playeritems_);
        } else {
          return playeritemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public int getPlayeritemsCount() {
        if (playeritemsBuilder_ == null) {
          return playeritems_.size();
        } else {
          return playeritemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto getPlayeritems(int index) {
        if (playeritemsBuilder_ == null) {
          return playeritems_.get(index);
        } else {
          return playeritemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public Builder setPlayeritems(
          int index, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto value) {
        if (playeritemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayeritemsIsMutable();
          playeritems_.set(index, value);
          onChanged();
        } else {
          playeritemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public Builder setPlayeritems(
          int index, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.Builder builderForValue) {
        if (playeritemsBuilder_ == null) {
          ensurePlayeritemsIsMutable();
          playeritems_.set(index, builderForValue.build());
          onChanged();
        } else {
          playeritemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public Builder addPlayeritems(com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto value) {
        if (playeritemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayeritemsIsMutable();
          playeritems_.add(value);
          onChanged();
        } else {
          playeritemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public Builder addPlayeritems(
          int index, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto value) {
        if (playeritemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayeritemsIsMutable();
          playeritems_.add(index, value);
          onChanged();
        } else {
          playeritemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public Builder addPlayeritems(
          com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.Builder builderForValue) {
        if (playeritemsBuilder_ == null) {
          ensurePlayeritemsIsMutable();
          playeritems_.add(builderForValue.build());
          onChanged();
        } else {
          playeritemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public Builder addPlayeritems(
          int index, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.Builder builderForValue) {
        if (playeritemsBuilder_ == null) {
          ensurePlayeritemsIsMutable();
          playeritems_.add(index, builderForValue.build());
          onChanged();
        } else {
          playeritemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public Builder addAllPlayeritems(
          java.lang.Iterable<? extends com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto> values) {
        if (playeritemsBuilder_ == null) {
          ensurePlayeritemsIsMutable();
          super.addAll(values, playeritems_);
          onChanged();
        } else {
          playeritemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public Builder clearPlayeritems() {
        if (playeritemsBuilder_ == null) {
          playeritems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          playeritemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public Builder removePlayeritems(int index) {
        if (playeritemsBuilder_ == null) {
          ensurePlayeritemsIsMutable();
          playeritems_.remove(index);
          onChanged();
        } else {
          playeritemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.Builder getPlayeritemsBuilder(
          int index) {
        return getPlayeritemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDtoOrBuilder getPlayeritemsOrBuilder(
          int index) {
        if (playeritemsBuilder_ == null) {
          return playeritems_.get(index);  } else {
          return playeritemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public java.util.List<? extends com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDtoOrBuilder> 
           getPlayeritemsOrBuilderList() {
        if (playeritemsBuilder_ != null) {
          return playeritemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(playeritems_);
        }
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.Builder addPlayeritemsBuilder() {
        return getPlayeritemsFieldBuilder().addBuilder(
            com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.Builder addPlayeritemsBuilder(
          int index) {
        return getPlayeritemsFieldBuilder().addBuilder(
            index, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.wabao.mogame.protocol.dto.player.PlayerItemDto playeritems = 1;</code>
       */
      public java.util.List<com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.Builder> 
           getPlayeritemsBuilderList() {
        return getPlayeritemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.Builder, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDtoOrBuilder> 
          getPlayeritemsFieldBuilder() {
        if (playeritemsBuilder_ == null) {
          playeritemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDto.Builder, com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.PlayerItemDtoOrBuilder>(
                  playeritems_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          playeritems_ = null;
        }
        return playeritemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.wabao.mogame.protocol.dto.player.PlayerDto)
    }

    static {
      defaultInstance = new PlayerDto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wabao.mogame.protocol.dto.player.PlayerDto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wabao_mogame_protocol_dto_player_PlayerDto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wabao_mogame_protocol_dto_player_PlayerDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:com/wabao/mogame/protocol/dto/player/P" +
      "layerDto_Proto.proto\022$com.wabao.mogame.p" +
      "rotocol.dto.player\032>com/wabao/mogame/pro" +
      "tocol/dto/player/PlayerItemDto_Proto.pro" +
      "to\"U\n\tPlayerDto\022H\n\013playeritems\030\001 \003(\01323.c" +
      "om.wabao.mogame.protocol.dto.player.Play" +
      "erItemDtoB\'\n%com.wabao.mogame.modules.pr" +
      "otocol.dto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wabao_mogame_protocol_dto_player_PlayerDto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wabao_mogame_protocol_dto_player_PlayerDto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wabao_mogame_protocol_dto_player_PlayerDto_descriptor,
              new java.lang.String[] { "Playeritems", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wabao.mogame.modules.protocol.dto.PlayerItemDtoProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
